version: "3.8"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"  # Ensure no other service is using this port
    environment:
      POSTGRES_DB: rootDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
