version: "3.8"

services:
  mongo:
    image: mongo:5.0    # specify the desired MongoDB version
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"   # ensure no other service uses this port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand({ ping: 1 }).ok' | mongo --quiet localhost:27017/test
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
